### ISSUE TITLE
关于账户管理的添加账户按钮点不了

### ISSUE THREAD

**Issue by hyq-immor** [Nusture/FamilyFinancialManagementSystem-vue#1]
关于账户管理的添加账户按钮点不了
![image](https://user-images.githubusercontent.com/119746813/205447970-fafc79ec-e0d6-45bf-a3f9-386e02a6f43b.png)

**Comment by Nusture** [comment]
检查一下是不是因为你前端的改动导致的这个问题 或者是后端配置错误又或者是因为登陆了没有添加账户权限的账号(如果是你改动导致的，那就只能靠你自己解决了)。这个项目只是一个为了毕设写的半成品，很久没有维护了，以后也说不定不会再维护了，所以我并不建议直接使用，如果你坚持使用的话，我建议把后端spark相关功能删除然后重写接口，spark的功能我只是纯粹为了应付毕设加上去的，因为我对spark不熟悉，所以当时写的spark仅限于能跑，而且经常会出问题(一般重启就会正常)

**Comment by hyq-immor** [comment]
哈哈哈，我似乎明白错哪了，感谢指点
